### ISSUE TITLE
Add Support for list of domains

### ISSUE THREAD

**Issue by attacker34** [MichaelStott/CRLF-Injection-Scanner#3]
Hi @MichaelStott 

Please add support for list of urls .

Sincerely,

**Comment by attacker34** [comment]
Sorry, I've just read the code... It was not in Readme file that's why opened it.

**Comment by MichaelStott** [comment]
@attacker34 No problem, I've updated the README to include this functionality.

**Comment by attacker34** [comment]
Hi @MichaelStott Can you please add support for list of payloads (payloads.txt) to be tested against each url (urls.txt )

Thanks.
